#!/bin/bash
# install-claude.sh - ~/.claude/rules/agent-toolkit/ に agent-toolkit ルールファイルを配置する。
#
# 会社マシンなど dotfiles 全体を導入できない環境向け。GitHub から最新のルールファイルを
# 一時ステージングディレクトリへダウンロードし、原子的リネームで配布先を差し替える。
#
# 使い方: Claude Code をインストールしたあとで以下を実行する。
#   curl -fsSL https://raw.githubusercontent.com/ak110/dotfiles/master/install-claude.sh | bash
#
# テスト時は DOTFILES_RULES_URL 環境変数でベース URL を差し替え可能。

set -euo pipefail

BASE_URL="${DOTFILES_RULES_URL:-https://raw.githubusercontent.com/ak110/dotfiles/master/agent-toolkit/rules}"
TARGET_DIR="$HOME/.claude/rules/agent-toolkit"
LEGACY_DIR="$HOME/.claude/rules/agent-basics"
# ステージング先は rules/ の外に置く。
# rules/ 配下に配置すると Claude Code が再帰的に読み込むため、差し替え中に二重ロードされる。
STAGE_ROOT="$HOME/.claude/rules-stage"

# 配布対象ファイル一覧。
# `scripts/gen-install-files.py`が`agent-toolkit/rules/*.md`から自動生成する。
# 手動編集せず、rules/配下の追加・削除後は同スクリプトを実行する（pre-commit hookが自動実行）。
# 3者の整合性は`agent-toolkit/scripts/install_script_ssot_test.py`で自動検証する。
# AUTOGENERATED-INSTALL-FILES BEGIN
FILES=(
    01-agent.md
    02-collaboration.md
    03-claude-code.md
    04-styles.md
    05-terminology.md
    06-monitoring.md
)
# AUTOGENERATED-INSTALL-FILES END

STAGE_DIR=""
OLD_DIR=""
# 差し替え完了後は OLD_DIR を削除扱いとするため本フラグで区別する（エラー時の復元を抑止）
REPLACED=0

_cleanup() {
    # エラー終了時に既存の TARGET_DIR を可能な限り復元する。
    if [ "$REPLACED" -eq 0 ] && [ -n "$OLD_DIR" ] && [ -d "$OLD_DIR" ] && [ ! -d "$TARGET_DIR" ]; then
        mv "$OLD_DIR" "$TARGET_DIR" 2>/dev/null || true
    fi
    # STAGE_DIR と OLD_DIR の残骸を削除する。
    [ -n "$STAGE_DIR" ] && [ -d "$STAGE_DIR" ] && rm -rf "$STAGE_DIR"
    [ -n "$OLD_DIR" ] && [ -d "$OLD_DIR" ] && rm -rf "$OLD_DIR"
    return 0
}
trap _cleanup EXIT

_download() {
    local name="$1"
    curl -fsSL "$BASE_URL/$name" -o "$STAGE_DIR/$name"
}

# agent-toolkit プラグインを user scope でインストール・更新する。
# 併せて旧 edit-guardrails プラグインを除去する（現在は agent-toolkit に統合されている）。
_install_agent_toolkit() {
    echo ""
    echo "agent-toolkit プラグインを user scope にインストール・更新します..."
    claude plugin marketplace add ak110/dotfiles --scope=user >/dev/null 2>&1 || true
    claude plugin marketplace update ak110-dotfiles >/dev/null 2>&1 || true
    claude plugin uninstall edit-guardrails@ak110-dotfiles >/dev/null 2>&1 || true
    claude plugin install agent-toolkit@ak110-dotfiles --scope=user >/dev/null 2>&1 || true
    claude plugin update agent-toolkit@ak110-dotfiles --scope=user >/dev/null 2>&1 || true
    echo "agent-toolkit プラグインの導入・更新を試行しました (旧 edit-guardrails は削除を試行しました)。"
}

# ~/.local/bin/atk へラッパーを配置する。
# インストール済み agent-toolkit プラグインの最新バージョンを動的解決するため、
# 参照先パス（cache/<marketplace>/agent-toolkit/<version>/bin/atk）を実行時に決定する形とする。
# 直接シンボリックリンクを作成するとバージョン更新のたびに追随が必要となるため、実行時解決のラッパーを採用する。
_install_atk_wrapper() {
    local bin_dir="$HOME/.local/bin"
    local wrapper="$bin_dir/atk"
    mkdir -p "$bin_dir"
    cat >"$wrapper" <<'EOF'
#!/bin/bash
# agent-toolkit プラグイン付属の atk コマンドを最新バージョンから起動するラッパー。
# install-claude.sh が生成する。更新したい場合は同スクリプトを再実行する。
set -euo pipefail
plugin_bin=$(ls -d "$HOME"/.claude/plugins/cache/*/agent-toolkit/*/bin 2>/dev/null | sort -V | tail -1)
if [ -z "$plugin_bin" ] || [ ! -x "$plugin_bin/atk" ]; then
    echo "atk: agent-toolkit プラグインが見つかりません。install-claude.sh を再実行してください。" >&2
    exit 1
fi
exec "$plugin_bin/atk" "$@"
EOF
    chmod +x "$wrapper"
    echo "配置: $wrapper"
    if ! (echo "$PATH" | tr ':' '\n' | grep -qxF "$bin_dir"); then
        echo "注意: '$bin_dir' が PATH に含まれていません。~/.bashrc 等で PATH に追加してください。" >&2
    fi
}

main() {
    if ! command -v claude >/dev/null 2>&1; then
        echo "Claude Code (claude CLI) が見つかりません。" >&2
        echo "Claude Code を先にインストールしてから本スクリプトを再実行してください。" >&2
        exit 1
    fi

    mkdir -p "$(dirname "$TARGET_DIR")" "$STAGE_ROOT"
    STAGE_DIR=$(mktemp -d "$STAGE_ROOT/agent-toolkit.stage.XXXXXX")

    for name in "${FILES[@]}"; do
        _download "$name"
    done

    # リネーム前の旧ファイル名を配布先から削除する（ダウンロード対象一覧との差分残置防止）。
    for legacy in 02-claude-code.md 03-styles.md 04-terminology.md; do
        rm -f "$TARGET_DIR/$legacy"
    done

    # 既存の TARGET_DIR を退避し、ステージングを差し替える。
    # mv は同一ファイルシステム上で原子的リネームとして動作する。
    if [ -d "$TARGET_DIR" ]; then
        OLD_DIR="$STAGE_ROOT/agent-toolkit.old.$$"
        mv "$TARGET_DIR" "$OLD_DIR"
    fi
    mv "$STAGE_DIR" "$TARGET_DIR"
    STAGE_DIR=""
    REPLACED=1
    echo "配置: $TARGET_DIR"

    if [ -n "$OLD_DIR" ] && [ -d "$OLD_DIR" ]; then
        rm -rf "$OLD_DIR"
        OLD_DIR=""
    fi

    if [ -d "$LEGACY_DIR" ]; then
        rm -rf "$LEGACY_DIR"
        echo "削除（旧ディレクトリ）: $LEGACY_DIR"
    fi

    _install_agent_toolkit
    _install_atk_wrapper
}

main "$@"
