Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# install-claude.ps1 - ~/.claude/rules/agent-toolkit/ に agent-toolkit ルールファイルを配置する。
#
# 会社マシンなど dotfiles 全体を導入できない環境向け。GitHub から最新のルールファイルを
# 一時ステージングディレクトリへダウンロードし、原子的リネームで配布先を差し替える。
#
# cmd からの使い方 (Claude Code、Codex、uv をインストールしたあとで実行する):
#   powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://raw.githubusercontent.com/ak110/dotfiles/master/install-claude.ps1 | iex"
#
# テスト時は DOTFILES_RULES_URL 環境変数でベース URL を差し替え可能。

$baseUrl = if ($env:DOTFILES_RULES_URL) { $env:DOTFILES_RULES_URL } else { 'https://raw.githubusercontent.com/ak110/dotfiles/master/agent-toolkit/rules' }
$targetDir = Join-Path $HOME '.claude/rules/agent-toolkit'
$legacyDir = Join-Path $HOME '.claude/rules/agent-basics'
# ステージング先は rules/ の外に置く。
# rules/ 配下に配置すると Claude Code が再帰的に読み込むため、差し替え中に二重ロードされる。
$stageRoot = Join-Path $HOME '.claude/rules-stage'
$codexPluginId = 'agent-toolkit@ak110-dotfiles'
$script:codexPluginUpdated = $false
$script:utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$codexHomeDir = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $HOME '.codex' }
$codexPluginCacheRoot = Join-Path $codexHomeDir 'plugins/cache/ak110-dotfiles/agent-toolkit'
$codexCacheCompatVersions = Join-Path $codexHomeDir 'plugins/cache-compat/ak110-dotfiles/agent-toolkit/versions'

# 配布対象ファイル一覧。
# `scripts/gen-install-files.py`が`agent-toolkit/rules/*.md`から自動生成する。
# 手動編集せず、rules/配下の追加・削除後は同スクリプトを実行する（pre-commit hookが自動実行）。
# 3者の整合性は`agent-toolkit/scripts/install_script_ssot_test.py`で自動検証する。
# AUTOGENERATED-INSTALL-FILES BEGIN
$files = @(
    '01-agent.md'
    '02-agent-operations.md'
    '99-claude-code.md'
)
# AUTOGENERATED-INSTALL-FILES END

function Invoke-Download {
    param([string]$url, [string]$destination)
    $client = New-Object System.Net.WebClient
    try {
        $client.DownloadFile($url, $destination)
    } finally {
        $client.Dispose()
    }
}

function Assert-Command {
    param([string]$name, [string]$productName, [string]$installUrl)
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        throw "$productName ($name CLI) が見つかりません。$installUrl を参照して先にインストールしてください。"
    }
}

function Invoke-RequiredNativeCommand {
    param([string]$command, [string[]]$arguments)
    & $command @arguments
    if ($LASTEXITCODE -ne 0) {
        throw "$command の実行に失敗しました（終了コード: $LASTEXITCODE）。"
    }
}

# agent-toolkit プラグインを user scope でインストール・更新する。
# 併せて旧 edit-guardrails プラグインを除去する（現在は agent-toolkit に統合されている）。
function Install-AgentToolkitPlugin {
    Write-Output ''
    Write-Output 'agent-toolkit プラグインを user scope にインストール・更新します...'
    & claude plugin marketplace add ak110/dotfiles --scope=user 2>&1 | Out-Null
    & claude plugin marketplace update ak110-dotfiles 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'Claude Codeマーケットプレイスの更新に失敗しました。' }
    & claude plugin uninstall 'edit-guardrails@ak110-dotfiles' 2>&1 | Out-Null
    & claude plugin install 'agent-toolkit@ak110-dotfiles' --scope=user 2>&1 | Out-Null
    & claude plugin update 'agent-toolkit@ak110-dotfiles' --scope=user 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'Claude Codeプラグインの更新に失敗しました。' }
    Write-Output 'Claude Code側のagent-toolkitプラグインを設定しました。'
}

function Get-CodexPluginState {
    $jsonLines = & codex plugin list --json 2>$null
    if ($LASTEXITCODE -ne 0) { return $null }
    try {
        $data = ($jsonLines -join "`n") | ConvertFrom-Json -ErrorAction Stop
    } catch {
        return $null
    }
    if ($null -eq $data -or $data.GetType() -ne [System.Management.Automation.PSCustomObject]) { return $null }
    $installedProperty = $data.PSObject.Properties['installed']
    if ($null -eq $installedProperty -or $installedProperty.Value -isnot [System.Array]) { return $null }
    $plugin = $null
    foreach ($item in @($installedProperty.Value)) {
        if ($null -eq $item -or $item.GetType() -ne [System.Management.Automation.PSCustomObject]) { return $null }
        $pluginIdProperty = $item.PSObject.Properties['pluginId']
        if ($null -eq $pluginIdProperty -or $pluginIdProperty.Value -isnot [string]) { return $null }
        if ($pluginIdProperty.Value -ne $codexPluginId) { continue }
        $versionProperty = $item.PSObject.Properties['version']
        $enabledProperty = $item.PSObject.Properties['enabled']
        if ($null -eq $versionProperty -or $versionProperty.Value -isnot [string] -or
            $null -eq $enabledProperty -or $enabledProperty.Value -isnot [bool]) {
            return $null
        }
        if ($null -eq $plugin) { $plugin = $item }
    }
    if ($null -eq $plugin) {
        return [PSCustomObject]@{ Present = $false; Version = $null; Enabled = $null }
    }
    return [PSCustomObject]@{
        Present = $true
        Version = $plugin.PSObject.Properties['version'].Value
        Enabled = $plugin.PSObject.Properties['enabled'].Value
    }
}

function Get-CodexExpectedPluginVersion {
    $jsonLines = & codex plugin marketplace list --json 2>$null
    if ($LASTEXITCODE -ne 0) { throw 'Codexマーケットプレイス一覧を取得できません。' }
    try {
        $data = ($jsonLines -join "`n") | ConvertFrom-Json -ErrorAction Stop
    } catch {
        throw 'Codexマーケットプレイス一覧をJSONとして読み取れません。'
    }
    foreach ($marketplace in @($data.marketplaces)) {
        if ($marketplace.name -ne 'ak110-dotfiles' -or $marketplace.root -isnot [string]) { continue }
        $manifestPath = Join-Path $marketplace.root 'agent-toolkit/.codex-plugin/plugin.json'
        try {
            $manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8 | ConvertFrom-Json -ErrorAction Stop
        } catch {
            throw "$manifestPath からCodex pluginのversionを取得できません。"
        }
        if ($manifest.version -isnot [string]) { throw "$manifestPath のversionが文字列ではありません。" }
        return $manifest.version
    }
    throw 'ak110-dotfilesマーケットプレイスの登録先を取得できません。'
}

function Test-CodexVersionName {
    param([string]$version)
    return $version -notin @('', '.', '..') -and $version -cmatch '^[A-Za-z0-9._+\-]+$'
}

function Get-CodexCacheVersionSet {
    $versions = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    if (Test-Path -LiteralPath $codexCacheCompatVersions -PathType Leaf) {
        foreach ($version in [System.IO.File]::ReadAllLines($codexCacheCompatVersions, [System.Text.Encoding]::UTF8)) {
            if (Test-CodexVersionName $version) {
                $null = $versions.Add($version)
            } else {
                [Console]::Error.WriteLine("不正なCodex plugin互換version名を無視します: '$version'")
            }
        }
    }
    if (Test-Path -LiteralPath $codexPluginCacheRoot -PathType Container) {
        foreach ($entry in Get-ChildItem -LiteralPath $codexPluginCacheRoot -Force) {
            $linkType = $entry.PSObject.Properties['LinkType']
            if (-not $entry.PSIsContainer -and ($null -eq $linkType -or -not $linkType.Value)) { continue }
            if (Test-CodexVersionName $entry.Name) {
                $null = $versions.Add($entry.Name)
            } else {
                [Console]::Error.WriteLine("不正なCodex plugin cache version名を無視します: '$($entry.Name)'")
            }
        }
    }
    return $versions
}

function Save-CodexCacheVersionLedger {
    $versionsDir = Split-Path $codexCacheCompatVersions -Parent
    New-Item -ItemType Directory -Path $versionsDir -Force | Out-Null
    $temporary = Join-Path $versionsDir ("versions." + [System.IO.Path]::GetRandomFileName())
    $backup = Join-Path $versionsDir ("versions.backup." + [System.IO.Path]::GetRandomFileName())
    try {
        $content = ((Get-CodexCacheVersionSet | Sort-Object -CaseSensitive) -join "`n")
        if ($content) { $content += "`n" }
        [System.IO.File]::WriteAllText($temporary, $content, $script:utf8NoBom)
        if (Test-Path -LiteralPath $codexCacheCompatVersions -PathType Leaf) {
            [System.IO.File]::Replace($temporary, $codexCacheCompatVersions, $backup)
        } else {
            [System.IO.File]::Move($temporary, $codexCacheCompatVersions)
        }
    } finally {
        if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force }
        if (Test-Path -LiteralPath $backup) { Remove-Item -LiteralPath $backup -Force }
    }
}

function Restore-CodexCacheLink {
    param([string]$currentVersion)
    if (-not (Test-Path -LiteralPath $codexCacheCompatVersions -PathType Leaf)) { return }
    $target = Join-Path $codexPluginCacheRoot $currentVersion
    foreach ($version in [System.IO.File]::ReadAllLines($codexCacheCompatVersions, [System.Text.Encoding]::UTF8)) {
        if (-not (Test-CodexVersionName $version)) {
            [Console]::Error.WriteLine("不正なCodex plugin互換version名を無視します: '$version'")
            continue
        }
        if ($version -eq $currentVersion) { continue }
        $targetItem = Get-Item -LiteralPath $target -Force -ErrorAction SilentlyContinue
        $targetLinkType = if ($null -eq $targetItem) { $null } else { $targetItem.PSObject.Properties['LinkType'] }
        if ($null -eq $targetItem -or -not $targetItem.PSIsContainer -or ($null -ne $targetLinkType -and $targetLinkType.Value)) {
            throw "現行Codex plugin cache実体が存在しません: $target"
        }
        $destination = Join-Path $codexPluginCacheRoot $version
        $entry = Get-Item -LiteralPath $destination -Force -ErrorAction SilentlyContinue
        if ($null -ne $entry) {
            $linkType = $entry.PSObject.Properties['LinkType']
            if ($null -eq $linkType -or -not $linkType.Value) {
                throw "通常entryとCodex plugin互換version名が競合しています: $destination"
            }
            if ($entry.Target -contains $target -or $entry.Target -contains $currentVersion) { continue }
            Remove-Item -LiteralPath $destination -Force
        }
        Invoke-CodexCacheLinkCreation $destination $target $currentVersion ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT)
    }
}

function Invoke-CodexCacheLinkCreation {
    param([string]$destination, [string]$target, [string]$currentVersion, [bool]$useJunction)
    if ($useJunction) {
        New-Item -ItemType Junction -Path $destination -Target $target | Out-Null
    } else {
        New-Item -ItemType SymbolicLink -Path $destination -Target $currentVersion | Out-Null
    }
}

function Test-CodexPluginStateChanged {
    param([object]$beforeState, [object]$afterState)
    if ($null -eq $beforeState -or $null -eq $afterState) { return $false }
    return $beforeState.Present -ne $afterState.Present -or
        $beforeState.Version -ne $afterState.Version -or
        $beforeState.Enabled -ne $afterState.Enabled
}

function Install-CodexPlugin {
    Write-Output 'Codex側のagent-toolkitプラグインを設定します...'
    & codex plugin marketplace add ak110/dotfiles --json 2>&1 | Out-Null
    Invoke-RequiredNativeCommand codex @('plugin', 'marketplace', 'upgrade', 'ak110-dotfiles', '--json')
    $expectedVersion = Get-CodexExpectedPluginVersion
    $beforeState = Get-CodexPluginState
    if ($null -eq $beforeState) { throw 'Codex plugin更新前の状態を確認できません。' }
    if ($beforeState.Present) {
        if ($beforeState.Version -ne $expectedVersion) { Save-CodexCacheVersionLedger }
    }
    Invoke-RequiredNativeCommand codex @('plugin', 'add', $codexPluginId, '--json')
    $afterState = Get-CodexPluginState
    $script:codexPluginUpdated = Test-CodexPluginStateChanged $beforeState $afterState
    if ($null -eq $afterState -or -not $afterState.Present -or -not $afterState.Enabled -or $afterState.Version -ne $expectedVersion) {
        throw 'Codex plugin更新後の状態が期待値と一致しません。'
    }
    Restore-CodexCacheLink $afterState.Version
    Write-Output 'Codex側のagent-toolkitプラグインを設定しました。'
}

function Write-CodexRestartNotice {
    [Console]::Error.WriteLine('Codex pluginを更新しました。実行中のCodexセッションを終了してから、次のコマンドでapp-server daemonを再起動してください。')
    [Console]::Error.WriteLine('codex app-server daemon restart')
}

function Test-CodexDaemonRunning {
    & codex app-server daemon version *> $null
    return $LASTEXITCODE -eq 0
}

function Test-UserCodexMcp {
    $configPath = Join-Path $HOME '.claude.json'
    if (-not (Test-Path -LiteralPath $configPath)) { return $false }

    try {
        $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json -ErrorAction Stop
    } catch {
        throw "$configPath をJSONとして読み取れないため、Codex MCPの設定を変更しません。"
    }
    if ($null -eq $config -or $config.GetType() -ne [System.Management.Automation.PSCustomObject]) {
        throw "$configPath のルートがJSONオブジェクトではないため、Codex MCPの設定を変更しません。"
    }

    $mcpProperty = $config.PSObject.Properties['mcpServers']
    if ($null -eq $mcpProperty) { return $false }
    if ($null -eq $mcpProperty.Value -or $mcpProperty.Value.GetType() -ne [System.Management.Automation.PSCustomObject]) {
        throw "$configPath のmcpServersがJSONオブジェクトではないため、Codex MCPの設定を変更しません。"
    }
    return $null -ne $mcpProperty.Value.PSObject.Properties['codex']
}

function Install-CodexMcp {
    if (Test-UserCodexMcp) {
        Write-Output 'Codex MCPはUser scopeへ登録済みです。既存設定を維持します。'
        return
    }
    Invoke-RequiredNativeCommand claude @('mcp', 'add', '--scope', 'user', 'codex', '--', 'codex', 'mcp-server')
    Write-Output 'Codex MCPをUser scopeへ登録しました。'
}

# ~/.local/bin/atk.cmd へラッパーを配置する。
# インストール済み agent-toolkit プラグインの最新バージョンを動的解決するため、
# 参照先パス（cache/<marketplace>/agent-toolkit/<version>/bin/atk.cmd）を実行時に決定する形とする。
# 直接コピーするとバージョン更新のたびに追随が必要となるため、実行時解決のラッパーを採用する。
function Install-AtkWrapper {
    $binDir = Join-Path $HOME '.local/bin'
    $wrapper = Join-Path $binDir 'atk.cmd'
    New-Item -ItemType Directory -Path $binDir -Force | Out-Null
    $body = @'
@echo off
setlocal enabledelayedexpansion
set "LATEST="
rem ディレクトリ名の辞書順ではなく、[version]型の自然順で最新実体を選択する。
for /f "usebackq delims=" %%A in (`powershell.exe -NoProfile -NonInteractive -Command "$root = Join-Path $env:USERPROFILE '.claude\plugins\cache'; Get-ChildItem -LiteralPath $root -Directory -ErrorAction SilentlyContinue | ForEach-Object { $plugin = Join-Path $_.FullName 'agent-toolkit'; if (Test-Path -LiteralPath $plugin -PathType Container) { Get-ChildItem -LiteralPath $plugin -Directory | ForEach-Object { $candidate = Join-Path $_.FullName 'bin\atk.cmd'; if (Test-Path -LiteralPath $candidate -PathType Leaf) { [PSCustomObject]@{ Version = [version]$_.Name; Path = $candidate } } } } } | Sort-Object Version -Descending | Select-Object -First 1 -ExpandProperty Path"`) do (
    if not defined LATEST set "LATEST=%%A"
)
if not defined LATEST goto :not_found
if not exist "%LATEST%" goto :not_found
call "%LATEST%" %*
exit /b %ERRORLEVEL%
:not_found
echo atk: agent-toolkit プラグインが見つかりません。install-claude.ps1 を再実行してください。 1>&2
exit /b 1
'@
    Set-Content -LiteralPath $wrapper -Value $body -Encoding ASCII
    Write-Output "配置: $wrapper"
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    if (-not ($userPath -split ';' | Where-Object { $_ -ieq $binDir })) {
        Write-Warning "'$binDir' がユーザー PATH に含まれていません。setx PATH ""%PATH%;$binDir"" 等で追加してください。"
    }
}

function Main {
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

    Assert-Command claude 'Claude Code' 'https://docs.anthropic.com/ja/docs/claude-code/overview'
    Assert-Command codex 'Codex' 'https://developers.openai.com/codex/cli/'
    Assert-Command uv 'uv' 'https://docs.astral.sh/uv/getting-started/installation/'

    New-Item -ItemType Directory -Path (Split-Path $targetDir -Parent) -Force | Out-Null
    New-Item -ItemType Directory -Path $stageRoot -Force | Out-Null

    $stageDir = Join-Path $stageRoot ("agent-toolkit.stage." + [System.IO.Path]::GetRandomFileName())
    New-Item -ItemType Directory -Path $stageDir -Force | Out-Null

    $oldDir = $null
    $replaced = $false
    try {
        foreach ($name in $files) {
            Invoke-Download "$baseUrl/$name" (Join-Path $stageDir $name)
        }

        # リネーム前の旧ファイル名を配布先から削除する（ダウンロード対象一覧との差分残置防止）。
        foreach ($legacy in @('02-claude-code.md', '03-styles.md', '04-terminology.md')) {
            Remove-Item -Path (Join-Path $targetDir $legacy) -Force -ErrorAction SilentlyContinue
        }

        if (Test-Path -LiteralPath $targetDir) {
            $oldDir = Join-Path $stageRoot ("agent-toolkit.old." + [System.IO.Path]::GetRandomFileName())
            Move-Item -LiteralPath $targetDir -Destination $oldDir
        }
        Move-Item -LiteralPath $stageDir -Destination $targetDir
        $stageDir = $null
        $replaced = $true
        Write-Output "配置: $targetDir"

        if ($oldDir -and (Test-Path -LiteralPath $oldDir)) {
            Remove-Item -LiteralPath $oldDir -Recurse -Force
            $oldDir = $null
        }

        if (Test-Path -LiteralPath $legacyDir) {
            Remove-Item -LiteralPath $legacyDir -Recurse -Force
            Write-Output "削除（旧ディレクトリ）: $legacyDir"
        }

        Install-AgentToolkitPlugin
        Install-CodexPlugin
        Install-CodexMcp
        Install-AtkWrapper
        Write-Output 'Claude Code・Codex、Codex MCP、atkの設定が完了しました。'
    } finally {
        # 差し替え前にエラー終了した場合、既存環境を復元する。
        if (-not $replaced -and $oldDir -and (Test-Path -LiteralPath $oldDir) -and -not (Test-Path -LiteralPath $targetDir)) {
            try { Move-Item -LiteralPath $oldDir -Destination $targetDir -ErrorAction Stop; $oldDir = $null } catch { $null = $_ }
        }
        if ($stageDir -and (Test-Path -LiteralPath $stageDir)) {
            Remove-Item -LiteralPath $stageDir -Recurse -Force -ErrorAction SilentlyContinue
        }
        if ($oldDir -and (Test-Path -LiteralPath $oldDir)) {
            Remove-Item -LiteralPath $oldDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}

$exitCode = 0
try {
    Main
} catch {
    $exitCode = 1
    [Console]::Error.WriteLine($_.Exception.Message)
}
if ($script:codexPluginUpdated -and (Test-CodexDaemonRunning)) {
    Write-CodexRestartNotice
}
exit $exitCode
