#!/bin/bash
# install-claude.sh - ~/.claude/rules/agent-toolkit/ に agent-toolkit ルールファイルを配置する。
#
# 会社マシンなど dotfiles 全体を導入できない環境向け。GitHub から最新のルールファイルを
# 一時ステージングディレクトリへダウンロードし、原子的リネームで配布先を差し替える。
#
# 使い方: Claude Code、Codex、uv をインストールしたあとで以下を実行する。
#   curl -fsSL https://raw.githubusercontent.com/ak110/dotfiles/master/install-claude.sh | bash
#
# テスト時は DOTFILES_RULES_URL 環境変数でベース URL を差し替え可能。

set -euo pipefail

BASE_URL="${DOTFILES_RULES_URL:-https://raw.githubusercontent.com/ak110/dotfiles/master/agent-toolkit/rules}"
TARGET_DIR="$HOME/.claude/rules/agent-toolkit"
LEGACY_DIR="$HOME/.claude/rules/agent-basics"
# ステージング先は rules/ の外に置く。
# rules/ 配下に配置すると Claude Code が再帰的に読み込むため、差し替え中に二重ロードされる。
STAGE_ROOT="$HOME/.claude/rules-stage"
CODEX_PLUGIN_ID="agent-toolkit@ak110-dotfiles"
CODEX_HOME_DIR="${CODEX_HOME:-$HOME/.codex}"
CODEX_PLUGIN_CACHE_ROOT="$CODEX_HOME_DIR/plugins/cache/ak110-dotfiles/agent-toolkit"
CODEX_CACHE_COMPAT_VERSIONS="$CODEX_HOME_DIR/plugins/cache-compat/ak110-dotfiles/agent-toolkit/versions"

# 配布対象ファイル一覧。
# `scripts/gen-install-files.py`が`agent-toolkit/rules/*.md`から自動生成する。
# 手動編集せず、rules/配下の追加・削除後は同スクリプトを実行する（pre-commit hookが自動実行）。
# 3者の整合性は`agent-toolkit/scripts/install_script_ssot_test.py`で自動検証する。
# AUTOGENERATED-INSTALL-FILES BEGIN
FILES=(
    01-agent.md
    02-agent-operations.md
    99-claude-code.md
)
# AUTOGENERATED-INSTALL-FILES END

STAGE_DIR=""
OLD_DIR=""
# 差し替え完了後は OLD_DIR を削除扱いとするため本フラグで区別する（エラー時の復元を抑止）
REPLACED=0
CODEX_PLUGIN_UPDATED=0

_cleanup() {
    # エラー終了時に既存の TARGET_DIR を可能な限り復元する。
    if [ "$REPLACED" -eq 0 ] && [ -n "$OLD_DIR" ] && [ -d "$OLD_DIR" ] && [ ! -d "$TARGET_DIR" ]; then
        mv "$OLD_DIR" "$TARGET_DIR" 2>/dev/null || true
    fi
    # STAGE_DIR と OLD_DIR の残骸を削除する。
    [ -n "$STAGE_DIR" ] && [ -d "$STAGE_DIR" ] && rm -rf "$STAGE_DIR"
    [ -n "$OLD_DIR" ] && [ -d "$OLD_DIR" ] && rm -rf "$OLD_DIR"
    return 0
}

_print_codex_restart_notice() {
    echo "Codex pluginを更新しました。実行中のCodexセッションを終了してから、次のコマンドでapp-server daemonを再起動してください。" >&2
    echo "codex app-server daemon restart" >&2
}

_codex_daemon_running() {
    codex app-server daemon version >/dev/null 2>&1
}

_on_exit() {
    local status=$?
    trap - EXIT
    _cleanup
    if [ "$CODEX_PLUGIN_UPDATED" -eq 1 ] && _codex_daemon_running; then
        _print_codex_restart_notice
    fi
    exit "$status"
}
trap _on_exit EXIT

_download() {
    local name="$1"
    curl -fsSL "$BASE_URL/$name" -o "$STAGE_DIR/$name"
}

_require_command() {
    local command_name="$1"
    local product_name="$2"
    local install_url="$3"
    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "$product_name ($command_name CLI) が見つかりません。" >&2
        echo "$install_url を参照して先にインストールしてください。" >&2
        return 1
    fi
}

# agent-toolkit プラグインを user scope でインストール・更新する。
# 併せて旧 edit-guardrails プラグインを除去する（現在は agent-toolkit に統合されている）。
_install_agent_toolkit() {
    echo ""
    echo "agent-toolkit プラグインを user scope にインストール・更新します..."
    claude plugin marketplace add ak110/dotfiles --scope=user >/dev/null 2>&1 || true
    claude plugin marketplace update ak110-dotfiles >/dev/null
    claude plugin uninstall edit-guardrails@ak110-dotfiles >/dev/null 2>&1 || true
    claude plugin install agent-toolkit@ak110-dotfiles --scope=user >/dev/null 2>&1 || true
    claude plugin update agent-toolkit@ak110-dotfiles --scope=user >/dev/null
    echo "Claude Code側のagent-toolkitプラグインを設定しました。"
}

_codex_plugin_state() {
    local plugin_json
    if ! plugin_json=$(codex plugin list --json); then
        return 1
    fi
    uv run --no-config --no-project --python 3 python - "$CODEX_PLUGIN_ID" "$plugin_json" <<'PY'
import json
import sys

plugin_id = sys.argv[1]
try:
    data = json.loads(sys.argv[2])
    installed = data["installed"]
except (json.JSONDecodeError, KeyError, TypeError):
    raise SystemExit(1)
if not isinstance(installed, list):
    raise SystemExit(1)
plugin = None
for item in installed:
    if not isinstance(item, dict) or not isinstance(item.get("pluginId"), str):
        raise SystemExit(1)
    if item["pluginId"] != plugin_id:
        continue
    version = item.get("version")
    enabled = item.get("enabled")
    if not isinstance(version, str) or not isinstance(enabled, bool):
        raise SystemExit(1)
    if plugin is None:
        plugin = {"enabled": enabled, "present": True, "version": version}
if plugin is None:
    print('{"present": false}')
else:
    print(json.dumps(plugin, sort_keys=True))
PY
}

_codex_state_value() {
    local state="$1"
    local key="$2"
    uv run --no-config --no-project --python 3 python - "$key" "$state" <<'PY'
import json
import sys

value = json.loads(sys.argv[2]).get(sys.argv[1])
if isinstance(value, bool):
    print(str(value).lower())
elif value is not None:
    print(value)
PY
}

_codex_expected_plugin_version() {
    local marketplace_json
    if ! marketplace_json=$(codex plugin marketplace list --json); then
        return 1
    fi
    uv run --no-config --no-project --python 3 python - "$marketplace_json" <<'PY'
import json
import pathlib
import sys

try:
    data = json.loads(sys.argv[1])
    marketplaces = data["marketplaces"]
except (json.JSONDecodeError, KeyError, TypeError):
    raise SystemExit(1)
for item in marketplaces:
    if isinstance(item, dict) and item.get("name") == "ak110-dotfiles" and isinstance(item.get("root"), str):
        manifest = pathlib.Path(item["root"]) / "agent-toolkit/.codex-plugin/plugin.json"
        try:
            version = json.loads(manifest.read_text(encoding="utf-8"))["version"]
        except (OSError, UnicodeError, json.JSONDecodeError, KeyError, TypeError):
            raise SystemExit(1)
        if not isinstance(version, str):
            raise SystemExit(1)
        print(version)
        raise SystemExit(0)
raise SystemExit(1)
PY
}

_valid_codex_version_name() {
    local value="$1"
    [ -n "$value" ] && [ "$value" != "." ] && [ "$value" != ".." ] && [[ "$value" =~ ^[A-Za-z0-9._+-]+$ ]]
}

_save_codex_cache_versions() {
    local state_dir
    local temporary
    local entry
    local version
    state_dir=$(dirname "$CODEX_CACHE_COMPAT_VERSIONS")
    mkdir -p "$state_dir"
    temporary=$(mktemp "$state_dir/versions.XXXXXX")
    if [ -f "$CODEX_CACHE_COMPAT_VERSIONS" ]; then
        while IFS= read -r version || [ -n "$version" ]; do
            if _valid_codex_version_name "$version"; then
                printf '%s\n' "$version" >>"$temporary"
            else
                echo "不正なCodex plugin互換version名を無視します: '$version'" >&2
            fi
        done <"$CODEX_CACHE_COMPAT_VERSIONS"
    fi
    if [ -d "$CODEX_PLUGIN_CACHE_ROOT" ]; then
        for entry in "$CODEX_PLUGIN_CACHE_ROOT"/*; do
            [ -e "$entry" ] || [ -L "$entry" ] || continue
            [ -d "$entry" ] || [ -L "$entry" ] || continue
            version=$(basename "$entry")
            if _valid_codex_version_name "$version"; then
                printf '%s\n' "$version" >>"$temporary"
            else
                echo "不正なCodex plugin cache version名を無視します: '$version'" >&2
            fi
        done
    fi
    sort -u "$temporary" -o "$temporary"
    mv "$temporary" "$CODEX_CACHE_COMPAT_VERSIONS"
}

_restore_codex_cache_links() {
    local current_version="$1"
    local target="$CODEX_PLUGIN_CACHE_ROOT/$current_version"
    local destination
    local link_target
    local version
    [ -f "$CODEX_CACHE_COMPAT_VERSIONS" ] || return 0
    while IFS= read -r version || [ -n "$version" ]; do
        if ! _valid_codex_version_name "$version"; then
            echo "不正なCodex plugin互換version名を無視します: '$version'" >&2
            continue
        fi
        [ "$version" != "$current_version" ] || continue
        if [ ! -d "$target" ] || [ -L "$target" ]; then
            echo "現行Codex plugin cache実体が存在しません: $target" >&2
            return 1
        fi
        destination="$CODEX_PLUGIN_CACHE_ROOT/$version"
        if [ -L "$destination" ]; then
            link_target=$(readlink "$destination")
            [ "$link_target" = "$current_version" ] && continue
            rm "$destination"
        elif [ -e "$destination" ]; then
            echo "通常entryとCodex plugin互換version名が競合しています: $destination" >&2
            return 1
        fi
        ln -s "$current_version" "$destination"
    done <"$CODEX_CACHE_COMPAT_VERSIONS"
}

_install_codex_plugin() {
    local before_state=""
    local before_state_known=0
    local before_present="false"
    local before_version=""
    local expected_version=""
    local after_state=""
    local after_present="false"
    local after_version=""
    local after_enabled="false"
    echo "Codex側のagent-toolkitプラグインを設定します..."
    codex plugin marketplace add ak110/dotfiles --json >/dev/null 2>&1 || true
    codex plugin marketplace upgrade ak110-dotfiles --json >/dev/null
    expected_version=$(_codex_expected_plugin_version)
    if ! before_state=$(_codex_plugin_state); then
        echo "Codex plugin更新前の状態を確認できません。" >&2
        return 1
    fi
    before_state_known=1
    before_present=$(_codex_state_value "$before_state" present)
    before_version=$(_codex_state_value "$before_state" version)
    if [ "$before_present" = "true" ] && [ "$before_version" != "$expected_version" ]; then
        _save_codex_cache_versions
    fi
    codex plugin add "$CODEX_PLUGIN_ID" --json >/dev/null
    if ! after_state=$(_codex_plugin_state); then
        echo "Codex plugin更新後の状態を確認できません。" >&2
        return 1
    fi
    after_present=$(_codex_state_value "$after_state" present)
    after_version=$(_codex_state_value "$after_state" version)
    after_enabled=$(_codex_state_value "$after_state" enabled)
    if [ "$before_state_known" -eq 1 ] && [ "$before_state" != "$after_state" ]; then
        CODEX_PLUGIN_UPDATED=1
    fi
    if [ "$after_present" != "true" ] || [ "$after_enabled" != "true" ] || [ "$after_version" != "$expected_version" ]; then
        echo "Codex plugin更新後の状態が期待値と一致しません。" >&2
        return 1
    fi
    _restore_codex_cache_links "$after_version"
    echo "Codex側のagent-toolkitプラグインを設定しました。"
}

_has_user_codex_mcp() {
    local config_path="$HOME/.claude.json"
    uv run --no-config --no-project --python 3 python - "$config_path" <<'PY'
import json
import pathlib
import sys

config_path = pathlib.Path(sys.argv[1])
if not config_path.exists():
    raise SystemExit(1)
try:
    config = json.loads(config_path.read_text(encoding="utf-8"))
except (OSError, UnicodeError, json.JSONDecodeError):
    raise SystemExit(2)
if not isinstance(config, dict):
    raise SystemExit(2)
if "mcpServers" not in config:
    raise SystemExit(1)
mcp_servers = config["mcpServers"]
if not isinstance(mcp_servers, dict):
    raise SystemExit(2)
raise SystemExit(0 if "codex" in mcp_servers else 1)
PY
}

_install_codex_mcp() {
    local status
    if _has_user_codex_mcp; then
        echo "Codex MCPはUser scopeへ登録済みです。既存設定を維持します。"
        return 0
    else
        status=$?
    fi

    if [ "$status" -eq 1 ]; then
        claude mcp add --scope user codex -- codex mcp-server >/dev/null
        echo "Codex MCPをUser scopeへ登録しました。"
        return 0
    fi

    echo "$HOME/.claude.jsonからCodex MCPのUser scope登録を判定できません。設定を変更せず終了します。" >&2
    return 1
}

# ~/.local/bin/atk へラッパーを配置する。
# インストール済み agent-toolkit プラグインの最新バージョンを動的解決するため、
# 参照先パス（cache/<marketplace>/agent-toolkit/<version>/bin/atk）を実行時に決定する形とする。
# 直接シンボリックリンクを作成するとバージョン更新のたびに追随が必要となるため、実行時解決のラッパーを採用する。
_install_atk_wrapper() {
    local bin_dir="$HOME/.local/bin"
    local wrapper="$bin_dir/atk"
    mkdir -p "$bin_dir"
    cat >"$wrapper" <<'EOF'
#!/bin/bash
# agent-toolkit プラグイン付属の atk コマンドを最新バージョンから起動するラッパー。
# install-claude.sh が生成する。更新したい場合は同スクリプトを再実行する。
set -euo pipefail
plugin_bin=$(ls -d "$HOME"/.claude/plugins/cache/*/agent-toolkit/*/bin 2>/dev/null | sort -V | tail -1)
if [ -z "$plugin_bin" ] || [ ! -x "$plugin_bin/atk" ]; then
    echo "atk: agent-toolkit プラグインが見つかりません。install-claude.sh を再実行してください。" >&2
    exit 1
fi
exec "$plugin_bin/atk" "$@"
EOF
    chmod +x "$wrapper"
    echo "配置: $wrapper"
    if ! (echo "$PATH" | tr ':' '\n' | grep -qxF "$bin_dir"); then
        echo "注意: '$bin_dir' が PATH に含まれていません。~/.bashrc 等で PATH に追加してください。" >&2
    fi
}

main() {
    _require_command claude "Claude Code" "https://docs.anthropic.com/ja/docs/claude-code/overview"
    _require_command codex "Codex" "https://developers.openai.com/codex/cli/"
    _require_command uv "uv" "https://docs.astral.sh/uv/getting-started/installation/"

    mkdir -p "$(dirname "$TARGET_DIR")" "$STAGE_ROOT"
    STAGE_DIR=$(mktemp -d "$STAGE_ROOT/agent-toolkit.stage.XXXXXX")

    for name in "${FILES[@]}"; do
        _download "$name"
    done

    # リネーム前の旧ファイル名を配布先から削除する（ダウンロード対象一覧との差分残置防止）。
    for legacy in 02-claude-code.md 03-styles.md 04-terminology.md; do
        rm -f "$TARGET_DIR/$legacy"
    done

    # 既存の TARGET_DIR を退避し、ステージングを差し替える。
    # mv は同一ファイルシステム上で原子的リネームとして動作する。
    if [ -d "$TARGET_DIR" ]; then
        OLD_DIR="$STAGE_ROOT/agent-toolkit.old.$$"
        mv "$TARGET_DIR" "$OLD_DIR"
    fi
    mv "$STAGE_DIR" "$TARGET_DIR"
    STAGE_DIR=""
    REPLACED=1
    echo "配置: $TARGET_DIR"

    if [ -n "$OLD_DIR" ] && [ -d "$OLD_DIR" ]; then
        rm -rf "$OLD_DIR"
        OLD_DIR=""
    fi

    if [ -d "$LEGACY_DIR" ]; then
        rm -rf "$LEGACY_DIR"
        echo "削除（旧ディレクトリ）: $LEGACY_DIR"
    fi

    _install_agent_toolkit
    _install_codex_plugin
    _install_codex_mcp
    _install_atk_wrapper
    echo "Claude Code・Codex、Codex MCP、atkの設定が完了しました。"
}

main "$@"
