
# 15秒ごとに生存確認パケットを送信・1回応答がなければ切断
ServerAliveInterval 15
ServerAliveCountMax 1
# SSH接続時にパケットの優先度（QoS/DSCP値）の付与を無効化（フレッツのIPv6など用）
IPQoS none

Host tqzh.tk
    User aki
    Port 24498

Host euryale
    Port 24498

Host *.sourceforge.jp
    User ak1

Host *.amazonaws.com
    User ubuntu

Host aws.tqzh.tk
    User ubuntu
