"""`scripts/`配下のテストが共有する補助関数と定数。

pytestのprependモードではリポジトリ直下と`scripts/`がともに`sys.path`へ入り、同名のトップレベルモジュールは
先に読み込んだ方だけが`sys.modules`に残る。直下の`_test_helpers.py`と衝突しないよう、本ファイルは別の名前にする。
"""

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
INSTALL_FILES_BEGIN = "AUTOGENERATED-INSTALL-FILES BEGIN"
INSTALL_FILES_END = "AUTOGENERATED-INSTALL-FILES END"
TWO_LAYER_WAIT_HEADING = "## agents_serverの二層待機"


def markdown_section(text: str, heading: str) -> str:
    """Markdown本文から見出し`heading`の直後から次のH1〜H3見出しまでを返す。"""
    match = re.search(rf"^{re.escape(heading)}\n(?P<body>.*?)(?=^#{{1,3}} |\Z)", text, re.MULTILINE | re.DOTALL)
    assert match is not None
    return match.group("body")


def extract_install_files_block(text: str) -> str:
    """導入スクリプトの自動生成ブロックをマーカー行ごと取り出し、改行をLFへそろえて返す。"""
    match = re.search(rf"# {re.escape(INSTALL_FILES_BEGIN)}.*?# {re.escape(INSTALL_FILES_END)}", text, re.DOTALL)
    assert match is not None
    return match.group(0).replace("\r\n", "\n")


def expected_sh_block(names: list[str]) -> str:
    """`install-claude.sh`の自動生成ブロックの期待値を返す。"""
    body = "\n".join(f"    {name}" for name in names)
    return f"# {INSTALL_FILES_BEGIN}\nFILES=(\n{body}\n)\n# {INSTALL_FILES_END}"


def expected_ps1_block(names: list[str]) -> str:
    """`install-claude.ps1`の自動生成ブロックの期待値を返す。"""
    body = "\n".join(f"    '{name}'" for name in names)
    return f"# {INSTALL_FILES_BEGIN}\n$files = @(\n{body}\n)\n# {INSTALL_FILES_END}"
