"""scripts/gen-install-files.py のテスト。

ファイル名にハイフンを含み通常のimport文で読み込めないため、`importlib`経由でロードする。
公開インターフェース`main()`経由で、実リポジトリの同期状態、模擬rules追加時の再生成、
マーカー欠落時のエラーを検証する。
"""

import dataclasses
import importlib.util
import pathlib
import re
import types

import pytest

_MODULE_PATH = pathlib.Path(__file__).resolve().parent / "gen-install-files.py"
_REPO_ROOT = _MODULE_PATH.parents[1]
_BEGIN = "AUTOGENERATED-INSTALL-FILES BEGIN"
_END = "AUTOGENERATED-INSTALL-FILES END"


def _load_module() -> types.ModuleType:
    """ハイフン付きファイル名のスクリプトを独立モジュールとしてロードする。"""
    spec = importlib.util.spec_from_file_location("gen_install_files", _MODULE_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@dataclasses.dataclass
class _Env:
    """テスト用の疑似リポジトリパス一式と対象モジュール。"""

    module: types.ModuleType
    rules_dir: pathlib.Path
    install_sh: pathlib.Path
    install_ps1: pathlib.Path


@pytest.fixture
def _env(tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch) -> _Env:
    """疑似リポジトリ構造をtmp_path配下に用意し、モジュール定数を差し替えて返す。"""
    module = _load_module()
    rules_dir = tmp_path / "agent-toolkit" / "rules"
    install_sh = tmp_path / "install-claude.sh"
    install_ps1 = tmp_path / "install-claude.ps1"
    rules_dir.mkdir(parents=True)
    install_sh.write_text(_script_with_block("FILES=(\n)\n"), encoding="utf-8")
    install_ps1.write_bytes(b"\xef\xbb\xbf" + _script_with_block("$files = @(\r\n)\r\n").encode("utf-8"))
    monkeypatch.setattr(module, "_RULES_DIR", rules_dir)
    monkeypatch.setattr(module, "_INSTALL_SH", install_sh)
    monkeypatch.setattr(module, "_INSTALL_PS1", install_ps1)
    return _Env(module=module, rules_dir=rules_dir, install_sh=install_sh, install_ps1=install_ps1)


def test_current_repo_files_are_synced() -> None:
    """リポジトリ実体のrules一覧と両install scriptのマーカーブロックが一致する。"""
    names = sorted(path.name for path in (_REPO_ROOT / "agent-toolkit" / "rules").glob("*.md"))
    sh_block = _extract_block((_REPO_ROOT / "install-claude.sh").read_text(encoding="utf-8"))
    ps1_block = _extract_block((_REPO_ROOT / "install-claude.ps1").read_text(encoding="utf-8-sig"))

    assert sh_block == _expected_sh_block(names)
    assert ps1_block == _expected_ps1_block(names)


def test_regenerate_with_added_rule(_env: _Env) -> None:
    """模擬rules配下のmdファイル一覧が両install scriptのブロックへ反映される。"""
    (_env.rules_dir / "02-collaboration.md").write_text("", encoding="utf-8")
    (_env.rules_dir / "01-agent.md").write_text("", encoding="utf-8")

    assert _env.module.main([]) == 0

    assert _extract_block(_env.install_sh.read_text(encoding="utf-8")) == _expected_sh_block(
        ["01-agent.md", "02-collaboration.md"]
    )
    ps1_bytes = _env.install_ps1.read_bytes()
    assert ps1_bytes.startswith(b"\xef\xbb\xbf")
    assert b"\r\n" in ps1_bytes
    assert _extract_block(ps1_bytes.decode("utf-8-sig")) == _expected_ps1_block(["01-agent.md", "02-collaboration.md"])


def test_missing_marker_raises(_env: _Env) -> None:
    """マーカーが欠落している場合はSystemExitで失敗する。"""
    _env.install_sh.write_text("FILES=()\n", encoding="utf-8")

    with pytest.raises(SystemExit, match="marker not found"):
        _env.module.main([])


def _script_with_block(block: str) -> str:
    return f"before\n# {_BEGIN}\n{block}# {_END}\nafter\n"


def _extract_block(text: str) -> str:
    match = re.search(rf"# {re.escape(_BEGIN)}.*?# {re.escape(_END)}", text, re.DOTALL)
    assert match is not None
    return match.group(0).replace("\r\n", "\n")


def _expected_sh_block(names: list[str]) -> str:
    body = "\n".join(f"    {name}" for name in names)
    return f"# {_BEGIN}\nFILES=(\n{body}\n)\n# {_END}"


def _expected_ps1_block(names: list[str]) -> str:
    body = "\n".join(f"    '{name}'" for name in names)
    return f"# {_BEGIN}\n$files = @(\n{body}\n)\n# {_END}"
