#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["pytilpack[quart]>=1.47.0"]
# ///
"""install scriptのFILES一覧をagent-toolkit/rules/*.mdから自動生成する。"""

import argparse
import pathlib
import re
import stat
import sys

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT))

from pytools._internal import claude_common  # pylint: disable=wrong-import-position  # noqa: E402

_RULES_DIR = _REPO_ROOT / "agent-toolkit" / "rules"
_INSTALL_SH = _REPO_ROOT / "install-claude.sh"
_INSTALL_PS1 = _REPO_ROOT / "install-claude.ps1"
_BEGIN = "AUTOGENERATED-INSTALL-FILES BEGIN"
_END = "AUTOGENERATED-INSTALL-FILES END"


def main(argv: list[str] | None = None) -> int:
    """Install scriptのFILES一覧を生成する。"""
    argparse.ArgumentParser(description="install scriptのFILES一覧を生成する。").parse_args(argv)

    names = _list_rules()
    outputs = (
        _build_output(_INSTALL_SH, _gen_sh_block(names)),
        _build_output(_INSTALL_PS1, _gen_ps1_block(names)),
    )
    for path, data, changed in outputs:
        if changed and not claude_common.atomic_write_bytes(path, data, tag="install files"):
            raise OSError(f"install scriptの書き込みに失敗: {path}")
    # 原子的書き込みは一時ファイルを生成して置き換えるため元ファイルの実行権限が失われる。
    # install-claude.shはshebangを持ち利用者がそのまま実行するファイルであり、
    # pre-commitのcheck-shebang-scripts-are-executableも実行権限を要求するため復元する。
    _INSTALL_SH.chmod(_INSTALL_SH.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return 0


def _list_rules() -> list[str]:
    """配布対象のrulesファイル名を辞書順で返す。"""
    return sorted(path.name for path in _RULES_DIR.glob("*.md"))


def _gen_sh_block(names: list[str]) -> str:
    body = "\n".join(f"    {name}" for name in names)
    return f"# {_BEGIN}\nFILES=(\n{body}\n)\n# {_END}"


def _gen_ps1_block(names: list[str]) -> str:
    body = "\n".join(f"    '{name}'" for name in names)
    return f"# {_BEGIN}\n$files = @(\n{body}\n)\n# {_END}"


def _build_output(path: pathlib.Path, new_block: str) -> tuple[pathlib.Path, bytes, bool]:
    text, had_bom, newline = _read_text(path)
    new_text = _replace_block(text, new_block, path)
    data = _encode_text(new_text, had_bom, newline)
    return path, data, new_text != text


def _read_text(path: pathlib.Path) -> tuple[str, bool, str]:
    data = path.read_bytes()
    had_bom = data.startswith(b"\xef\xbb\xbf")
    if had_bom:
        data = data[3:]
    newline = "\r\n" if b"\r\n" in data else "\n"
    return data.decode("utf-8").replace("\r\n", "\n"), had_bom, newline


def _encode_text(text: str, had_bom: bool, newline: str) -> bytes:
    data = text.replace("\n", newline).encode("utf-8")
    if had_bom:
        data = b"\xef\xbb\xbf" + data
    return data


def _replace_block(text: str, new_block: str, path: pathlib.Path) -> str:
    pattern = re.compile(rf"# {re.escape(_BEGIN)}.*?# {re.escape(_END)}", re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(f"marker not found in {path}")
    return pattern.sub(new_block, text)


if __name__ == "__main__":
    sys.exit(main())
