# ruff: noqa: E402,E501,F401,F811,I001
# pylint: disable=invalid-name,wrong-import-order,wrong-import-position
# pylint: disable=function-redefined,pointless-string-statement,undefined-variable,ungrouped-imports,unused-import,unused-wildcard-import,wildcard-import,wrong-import-order,wrong-import-position
"""分割前の公開契約を維持する責務別実装パッケージ。"""

import sys
import types

from _atk.serve.plans import roots as _roots
from _atk.serve.plans import rendering as _rendering
from _atk.serve.plans import ctime_index as _ctime_index
from _atk.serve.plans import local_scan as _local_scan
from _atk.serve.plans import remote as _remote
from _atk.serve.plans import views as _views

_MODULES = (
    _roots,
    _rendering,
    _ctime_index,
    _local_scan,
    _remote,
    _views,
)

for _target in _MODULES:
    for _source in _MODULES:
        for _name, _value in vars(_source).items():
            if not _name.startswith("__"):
                vars(_target).setdefault(_name, _value)

for _source in _MODULES:
    for _name, _value in vars(_source).items():
        if not _name.startswith("__"):
            globals().setdefault(_name, _value)

from _atk.serve.plans.roots import (
    logger,
    NEW_SOURCE_ID,
    LEGACY_SOURCE_ID,
    NEW_PORTABLE_ROOT,
    LEGACY_PORTABLE_ROOT,
    _UNRESOLVED_PRIVATE_NOTES_ROOT,
    _DETAIL_SUFFIX,
    _BUGS_SUFFIX,
    _TARGET_TSV_SUFFIXES,
    _LISTED_EXCLUDED_SUFFIXES,
    _PLAN_SUFFIX_LABELS,
    _REVIEW_TABLE_HEADERS,
    _BROADCAST_DEBOUNCE_SEC,
    _SSE_REFRESH_PAYLOAD,
    _WATCHED_EVENT_TYPES,
    MARKDOWN_CACHE_MAX_ENTRIES,
    MARKDOWN_CACHE_MAX_BYTES,
    _CREATION_TIME_INDEX_PATH,
    _LEGACY_CACHE_NAME_RE,
    _LEGACY_TEMPORARY_NAME_RE,
    SSH_BASE_OPTIONS,
    SSH_TIMEOUT_SEC,
    STDERR_EXCERPT_MAX_CHARS,
    RPC_REQUEST_TIMEOUT_SEC,
    DEFAULT_REMOTE_SEARCH_LIMIT,
    SSH_WATCH_OPTIONS,
    REMOTE_BACKOFF_INITIAL_SEC,
    REMOTE_BACKOFF_MAX_SEC,
    REMOTE_BACKOFF_JITTER_RANGE,
    REMOTE_STREAM_LIMIT_BYTES,
    TERMINATE_GRACE_TIMEOUT_SEC,
    SshRunner,
    LineSource,
    _PYGMENTS_FORMATTER,
    _PYGMENTS_CSS_CLASS,
    RootSpec,
    FileEntry,
    BroadcastState,
    make_file_entry,
    normalize_root_specs,
    _canonical,
    explicit_root_spec,
    _private_notes_result,
    default_root_specs,
    subscribe,
    unsubscribe,
    schedule_broadcast,
    _debounced_deliver,
    deliver_refresh,
    deliver_host_status,
    deliver_host_info,
    deliver_root_info,
    deliver_root_status,
    _broadcast,
    asyncio,
    _async_subprocess,
    base64,
    collections,
    contextlib,
    dataclasses,
    datetime,
    hashlib,
    html_lib,
    importlib,
    json,
    logging,
    os,
    pathlib,
    random,
    re,
    socket,
    subprocess,
    typing,
    markdown_it,
    platformdirs,
    pygments,
    watchdog,
    _file_lock,
    HtmlFormatter,
    get_lexer_by_name,
    ClassNotFound,
    _atk_serve_remote,
    TYPE_CHECKING,
)
from _atk.serve.plans.rendering import (
    _highlight_code,
    _render_fence,
    make_md_renderer,
    markdown_to_html,
    MarkdownCacheKey,
    MarkdownCache,
)
from _atk.serve.plans.ctime_index import (
    _exclusive_file_lock,
    _index_lock_path,
    _enter_index_lock,
    _index_key,
    _root_key,
    _entry_ctime,
    _load_index,
    _load_legacy_entries,
    _write_index,
    update_creation_time_index,
    cleanup_creation_time_temporaries,
)
from _atk.serve.plans.local_scan import (
    _STATIC_DIR,
    REMOTE_BOOTSTRAP,
    is_target_path,
    is_listed_path,
    PlansEventHandler,
    _ctime_epoch,
    local_host_info,
    root_info,
    root_warning,
    root_status,
    scan_files,
    list_files,
    search_files,
    resolve_under_root,
    read_mermaid_bundle,
    read_pygments_css,
)
from _atk.serve.plans.remote import (
    _build_remote_command_argv,
    RemoteHelperError,
    _stderr_excerpt,
    default_ssh_runner,
    _decode_read_payload,
    fetch_remote_file,
    RemoteSearchSuperseded,
    RemoteSearchResult,
    RemoteSearchRunner,
    _PendingSearch,
    RemoteSearchCoordinator,
    search_remote_files,
    _decode_root_info,
    _decode_root_status,
    _is_listed_remote_path,
    RemoteWatcher,
    _iter_stream_lines,
    _drain_stderr,
    _terminate_process,
    _wait_with_timeout,
    is_safe_remote_relpath,
)
from _atk.serve.plans.views import (
    PlansContext,
    create_context,
    _scan_local_root,
    _oldest_host_per_file,
    all_entries,
    listed_plan_path,
    search_entries,
    _search_remote,
    resolve_source_id,
    review_table_html,
    is_review_table_path,
    _plan_paths,
    plan_links_html,
    _plan_exists,
    PlanFileError,
    resolve_text_and_mtime,
    _read_with_mtime,
    render_file_html,
    start_local_watchers,
    stop_local_watchers,
    start_remote_watchers,
    stop_remote_watchers,
)


class _PackageModule(types.ModuleType):
    def __setattr__(self, name, value):
        super().__setattr__(name, value)
        for module in _MODULES:
            if name in vars(module):
                setattr(module, name, value)


sys.modules[__name__].__class__ = _PackageModule

__all__ = [
    "BroadcastState",
    "ClassNotFound",
    "DEFAULT_REMOTE_SEARCH_LIMIT",
    "FileEntry",
    "HtmlFormatter",
    "LEGACY_PORTABLE_ROOT",
    "LEGACY_SOURCE_ID",
    "LineSource",
    "MARKDOWN_CACHE_MAX_BYTES",
    "MARKDOWN_CACHE_MAX_ENTRIES",
    "MarkdownCache",
    "MarkdownCacheKey",
    "NEW_PORTABLE_ROOT",
    "NEW_SOURCE_ID",
    "PlanFileError",
    "PlansContext",
    "PlansEventHandler",
    "REMOTE_BACKOFF_INITIAL_SEC",
    "REMOTE_BACKOFF_JITTER_RANGE",
    "REMOTE_BACKOFF_MAX_SEC",
    "REMOTE_BOOTSTRAP",
    "REMOTE_STREAM_LIMIT_BYTES",
    "RPC_REQUEST_TIMEOUT_SEC",
    "RemoteHelperError",
    "RemoteSearchCoordinator",
    "RemoteSearchResult",
    "RemoteSearchRunner",
    "RemoteSearchSuperseded",
    "RemoteWatcher",
    "RootSpec",
    "SSH_BASE_OPTIONS",
    "SSH_TIMEOUT_SEC",
    "SSH_WATCH_OPTIONS",
    "STDERR_EXCERPT_MAX_CHARS",
    "SshRunner",
    "TERMINATE_GRACE_TIMEOUT_SEC",
    "TYPE_CHECKING",
    "_BROADCAST_DEBOUNCE_SEC",
    "_BUGS_SUFFIX",
    "_CREATION_TIME_INDEX_PATH",
    "_DETAIL_SUFFIX",
    "_LEGACY_CACHE_NAME_RE",
    "_LEGACY_TEMPORARY_NAME_RE",
    "_LISTED_EXCLUDED_SUFFIXES",
    "_PLAN_SUFFIX_LABELS",
    "_PYGMENTS_CSS_CLASS",
    "_PYGMENTS_FORMATTER",
    "_PendingSearch",
    "_REVIEW_TABLE_HEADERS",
    "_SSE_REFRESH_PAYLOAD",
    "_STATIC_DIR",
    "_TARGET_TSV_SUFFIXES",
    "_UNRESOLVED_PRIVATE_NOTES_ROOT",
    "_WATCHED_EVENT_TYPES",
    "_async_subprocess",
    "_atk_serve_remote",
    "_broadcast",
    "_build_remote_command_argv",
    "_canonical",
    "_ctime_epoch",
    "_debounced_deliver",
    "_decode_read_payload",
    "_decode_root_info",
    "_decode_root_status",
    "_drain_stderr",
    "_enter_index_lock",
    "_entry_ctime",
    "_exclusive_file_lock",
    "_file_lock",
    "_highlight_code",
    "_index_key",
    "_index_lock_path",
    "_is_listed_remote_path",
    "_iter_stream_lines",
    "_load_index",
    "_load_legacy_entries",
    "_oldest_host_per_file",
    "_plan_exists",
    "_plan_paths",
    "_private_notes_result",
    "_read_with_mtime",
    "_render_fence",
    "_root_key",
    "_scan_local_root",
    "_search_remote",
    "_stderr_excerpt",
    "_terminate_process",
    "_wait_with_timeout",
    "_write_index",
    "all_entries",
    "asyncio",
    "base64",
    "cleanup_creation_time_temporaries",
    "collections",
    "contextlib",
    "create_context",
    "dataclasses",
    "datetime",
    "default_root_specs",
    "default_ssh_runner",
    "deliver_host_info",
    "deliver_host_status",
    "deliver_refresh",
    "deliver_root_info",
    "deliver_root_status",
    "explicit_root_spec",
    "fetch_remote_file",
    "get_lexer_by_name",
    "hashlib",
    "html_lib",
    "importlib",
    "is_listed_path",
    "is_review_table_path",
    "is_safe_remote_relpath",
    "is_target_path",
    "json",
    "list_files",
    "listed_plan_path",
    "local_host_info",
    "logger",
    "logging",
    "make_file_entry",
    "make_md_renderer",
    "markdown_it",
    "markdown_to_html",
    "normalize_root_specs",
    "os",
    "pathlib",
    "plan_links_html",
    "platformdirs",
    "pygments",
    "random",
    "re",
    "read_mermaid_bundle",
    "read_pygments_css",
    "render_file_html",
    "resolve_source_id",
    "resolve_text_and_mtime",
    "resolve_under_root",
    "review_table_html",
    "root_info",
    "root_status",
    "root_warning",
    "scan_files",
    "schedule_broadcast",
    "search_entries",
    "search_files",
    "search_remote_files",
    "socket",
    "start_local_watchers",
    "start_remote_watchers",
    "stop_local_watchers",
    "stop_remote_watchers",
    "subprocess",
    "subscribe",
    "typing",
    "unsubscribe",
    "update_creation_time_index",
    "watchdog",
]
