# ruff: noqa: E402,E501,F401,F811,I001
# pylint: disable=invalid-name,wrong-import-order,wrong-import-position
# pylint: disable=duplicate-code,function-redefined,pointless-string-statement,undefined-variable,ungrouped-imports,unused-import,unused-wildcard-import,wildcard-import,wrong-import-order,wrong-import-position
# ruff: noqa: E402,E501,F401,F811,I001
# pylint: disable=invalid-name,wrong-import-order,wrong-import-position
# pylint: disable=duplicate-code,function-redefined,pointless-string-statement,undefined-variable,unused-import,unused-wildcard-import,wildcard-import,wrong-import-order,wrong-import-position
"""分割前の公開契約を維持する責務別実装パッケージ。"""

import sys
import types

from _atk.managed_temp import windows_security as _windows_security
from _atk.managed_temp import registry as _registry
from _atk.managed_temp import creation as _creation
from _atk.managed_temp import inventory as _inventory
from _atk.managed_temp import cli as _cli

_MODULES = (
    _windows_security,
    _registry,
    _creation,
    _inventory,
    _cli,
)

for _target in _MODULES:
    for _source in _MODULES:
        for _name, _value in vars(_source).items():
            if not _name.startswith("__"):
                vars(_target).setdefault(_name, _value)

for _source in _MODULES:
    for _name, _value in vars(_source).items():
        if not _name.startswith("__"):
            globals().setdefault(_name, _value)

from _atk.managed_temp.windows_security import (
    _AceHeader,
    _AccessAllowedAce,
    _Acl,
    _AclSizeInformation,
    _FileTime,
    _ByHandleFileInformation,
    _WindowsAce,
    _WindowsSecurity,
    _windows_dll,
    _windows_error,
    _windows_handle_open_error,
    _windows_sid_bytes,
    _windows_equal_sids,
    _windows_path_handle,
    _windows_security_update_handle,
    _windows_current_sid,
    _windows_information_identity,
    _windows_secure_path,
    _windows_replace_security,
    _windows_acl_buffer,
    _windows_set_security,
    _windows_security_descriptor,
    _windows_security_from_handle,
    _windows_security_base_is_valid,
    _windows_current_user_ace_is_valid,
    _windows_external_writer_ace_is_valid,
    _validate_windows_security,
    _validate_windows_managed_root_security,
    _windows_managed_root_security_is_valid,
    _windows_identity,
    argparse,
    contextlib,
    ctypes,
    datetime,
    enum,
    hashlib,
    json,
    os,
    pathlib,
    re,
    secrets,
    shutil,
    stat,
    sys,
    tempfile,
    typing,
    unicodedata,
    wintypes,
    _atk_help,
    TYPE_CHECKING,
)
from _atk.managed_temp.registry import (
    _MARKER_NAME,
    _SCHEMA_VERSION,
    _PREFIX_RE,
    _PREFIX_RULES,
    _UTC_ISO8601_RE,
    MAX_AGE_DAYS,
    _WINDOWS_ACCESS_ALLOWED_ACE_TYPE,
    _WINDOWS_ACCESS_DENIED_ACE_TYPE,
    _WINDOWS_ACL_REVISION,
    _WINDOWS_ERROR_ACCESS_DENIED,
    _WINDOWS_CONTAINER_INHERIT_ACE,
    _WINDOWS_DACL_SECURITY_INFORMATION,
    _WINDOWS_EXTERNAL_WRITER_ACCESS,
    _WINDOWS_FILE_ALL_ACCESS,
    _WINDOWS_FILE_ATTRIBUTE_DIRECTORY,
    _WINDOWS_FILE_FLAG_BACKUP_SEMANTICS,
    _WINDOWS_FILE_FLAG_OPEN_REPARSE_POINT,
    _WINDOWS_FILE_SHARE_ALL,
    _WINDOWS_OBJECT_INHERIT_ACE,
    _WINDOWS_OPEN_EXISTING,
    _WINDOWS_OWNER_SECURITY_INFORMATION,
    _WINDOWS_PROTECTED_DACL_SECURITY_INFORMATION,
    _WINDOWS_READ_ATTRIBUTES,
    _WINDOWS_READ_CONTROL,
    _WINDOWS_REPARSE_POINT,
    _WINDOWS_SE_DACL_PROTECTED,
    _WINDOWS_SE_FILE_OBJECT,
    _WINDOWS_SYNCHRONIZE,
    _WINDOWS_WRITE_DAC,
    _WINDOWS_WRITE_OWNER,
    ManagedTempError,
    _ManagedTempEntry,
    _WindowsApiError,
    _WindowsHandleOpenError,
    _ValidatedTemp,
    _ValidatedRoot,
    _temp_root,
    _validate_root,
    _owner_record,
    _state_root_path,
    _state_root,
    _registry_name,
    _registry_path,
    _write_private_json,
    _load_private_json,
    _path_identity,
    _record_base,
    _record,
    _is_utc_iso8601,
    _awis_are_valid,
    _records_match,
    _record_mismatch_error,
    _write_marker,
    _load_marker,
)
from _atk.managed_temp.creation import (
    prefix_violation,
    is_valid_prefix,
    _invalid_prefix_error,
    _remove_created_target,
    create_managed_temp,
    _validate_path_shape,
    _validate_posix,
    _validate_windows,
    validate_managed_temp,
)
from _atk.managed_temp.inventory import (
    is_missing_registered_temp,
    _cleanup_missing_registered_temp,
    _entity_absence_is_confirmed,
    _consuming_registry_path,
    _QuarantineState,
    _QuarantineJudgement,
    _lstat_or_none,
    _classify_quarantine,
    _restore_interrupted_consume,
    _cleanup_quarantine,
    _unregistered_candidates,
    count_unregistered_candidates,
    _marker_recovery_is_accepted,
    _report_unregistered_candidates,
    list_managed_temp,
    sweep_expired_managed_temp,
    _clear_directory,
    _restore_posix_quarantine,
    _tree_snapshot,
    _consume_registry,
    _restore_registry,
    _restore_cleanup_marker,
    _restore_cleanup_state,
    _cleanup_posix,
    _cleanup_windows,
    cleanup_managed_temp,
)
from _atk.managed_temp.cli import build_parser, dispatch, main


class _PackageModule(types.ModuleType):
    def __setattr__(self, name, value):
        super().__setattr__(name, value)
        for module in _MODULES:
            if name in vars(module):
                setattr(module, name, value)


sys.modules[__name__].__class__ = _PackageModule

__all__ = [
    "MAX_AGE_DAYS",
    "ManagedTempError",
    "TYPE_CHECKING",
    "_AccessAllowedAce",
    "_AceHeader",
    "_Acl",
    "_AclSizeInformation",
    "_ByHandleFileInformation",
    "_FileTime",
    "_MARKER_NAME",
    "_ManagedTempEntry",
    "_PREFIX_RE",
    "_PREFIX_RULES",
    "_QuarantineJudgement",
    "_QuarantineState",
    "_SCHEMA_VERSION",
    "_UTC_ISO8601_RE",
    "_ValidatedRoot",
    "_ValidatedTemp",
    "_WINDOWS_ACCESS_ALLOWED_ACE_TYPE",
    "_WINDOWS_ACCESS_DENIED_ACE_TYPE",
    "_WINDOWS_ACL_REVISION",
    "_WINDOWS_CONTAINER_INHERIT_ACE",
    "_WINDOWS_DACL_SECURITY_INFORMATION",
    "_WINDOWS_ERROR_ACCESS_DENIED",
    "_WINDOWS_EXTERNAL_WRITER_ACCESS",
    "_WINDOWS_FILE_ALL_ACCESS",
    "_WINDOWS_FILE_ATTRIBUTE_DIRECTORY",
    "_WINDOWS_FILE_FLAG_BACKUP_SEMANTICS",
    "_WINDOWS_FILE_FLAG_OPEN_REPARSE_POINT",
    "_WINDOWS_FILE_SHARE_ALL",
    "_WINDOWS_OBJECT_INHERIT_ACE",
    "_WINDOWS_OPEN_EXISTING",
    "_WINDOWS_OWNER_SECURITY_INFORMATION",
    "_WINDOWS_PROTECTED_DACL_SECURITY_INFORMATION",
    "_WINDOWS_READ_ATTRIBUTES",
    "_WINDOWS_READ_CONTROL",
    "_WINDOWS_REPARSE_POINT",
    "_WINDOWS_SE_DACL_PROTECTED",
    "_WINDOWS_SE_FILE_OBJECT",
    "_WINDOWS_SYNCHRONIZE",
    "_WINDOWS_WRITE_DAC",
    "_WINDOWS_WRITE_OWNER",
    "_WindowsAce",
    "_WindowsApiError",
    "_WindowsHandleOpenError",
    "_WindowsSecurity",
    "_atk_help",
    "_awis_are_valid",
    "_classify_quarantine",
    "_cleanup_missing_registered_temp",
    "_cleanup_posix",
    "_cleanup_quarantine",
    "_cleanup_windows",
    "_clear_directory",
    "_consume_registry",
    "_consuming_registry_path",
    "_entity_absence_is_confirmed",
    "_invalid_prefix_error",
    "_is_utc_iso8601",
    "_load_marker",
    "_load_private_json",
    "_lstat_or_none",
    "_marker_recovery_is_accepted",
    "_owner_record",
    "_path_identity",
    "_record",
    "_record_base",
    "_record_mismatch_error",
    "_records_match",
    "_registry_name",
    "_registry_path",
    "_remove_created_target",
    "_report_unregistered_candidates",
    "_restore_cleanup_marker",
    "_restore_cleanup_state",
    "_restore_interrupted_consume",
    "_restore_posix_quarantine",
    "_restore_registry",
    "_state_root",
    "_state_root_path",
    "_temp_root",
    "_tree_snapshot",
    "_unregistered_candidates",
    "_validate_path_shape",
    "_validate_posix",
    "_validate_root",
    "_validate_windows",
    "_validate_windows_managed_root_security",
    "_validate_windows_security",
    "_windows_acl_buffer",
    "_windows_current_sid",
    "_windows_current_user_ace_is_valid",
    "_windows_dll",
    "_windows_equal_sids",
    "_windows_error",
    "_windows_external_writer_ace_is_valid",
    "_windows_handle_open_error",
    "_windows_identity",
    "_windows_information_identity",
    "_windows_managed_root_security_is_valid",
    "_windows_path_handle",
    "_windows_replace_security",
    "_windows_secure_path",
    "_windows_security_base_is_valid",
    "_windows_security_descriptor",
    "_windows_security_from_handle",
    "_windows_security_update_handle",
    "_windows_set_security",
    "_windows_sid_bytes",
    "_write_marker",
    "_write_private_json",
    "argparse",
    "build_parser",
    "cleanup_managed_temp",
    "contextlib",
    "count_unregistered_candidates",
    "create_managed_temp",
    "ctypes",
    "datetime",
    "dispatch",
    "enum",
    "hashlib",
    "is_missing_registered_temp",
    "is_valid_prefix",
    "json",
    "list_managed_temp",
    "main",
    "os",
    "pathlib",
    "prefix_violation",
    "re",
    "secrets",
    "shutil",
    "stat",
    "sweep_expired_managed_temp",
    "sys",
    "tempfile",
    "typing",
    "unicodedata",
    "validate_managed_temp",
    "wintypes",
]
